Fallback to wget in eccc if cURL is not available.

diff --git a/eccc/eccc b/eccc/eccc
--- a/eccc/eccc
+++ b/eccc/eccc
@@ -1,10 +1,11 @@
 # /bin/env bash
 # Author:   Conor I. Anderson <conor@conr.ca>
 # Date:     2018-06-29
-# Last mod: 2019-01-01
+# Last mod: 2019-01-14
 #
 # Changelog:
 # 
+# 2019-01-14: Fallback to wget if cURL is not available.
 # 2019-01-01: Be a good netizen: Sleep 0.5 secs between curl requests.
 #
 # 2018-11-09: Use curl instead of wget to reduce dependencies on Mac.
@@ -26,14 +27,11 @@ Options:
                    If no month is given, 1:12 will be used. (only applies to hourly data)
     -t [timeframe] Timeframe to download. 1 is hourly; 2 is daily; 3 is monthly (defaults to 2)
     -g             Optional; if specified, we will attempt to glue individual CSV files into a single file.
-                   This will not work if the skip option, above, is not specified.
     -h             Show this help text
 
 Deprecated options: These options should no longer be neccesary and may be removed in a future update
 
     -x [skip]      Optional; a fixed number of lines to be cropped from the top of each file.
-                   e.g. for monthly: 18; for daily: 24; for hourly: 15. Add 1 to daily and hourly
-                   for data that is newer than May 2018 (an additional metadata field was added).
 
 Examples:
 ${0##*/} -s 5051 -y 1981:2010 -g # creates a single daily .csv file for Toronto daily data
@@ -117,6 +115,18 @@ else
   fi
 fi
 
+if command -v curl >/dev/null 2>&1; then
+  CMD=curl
+else
+  if command -v wget >/dev/null 2>&1; then
+    echo "cURL is not installed. Falling back to wget."
+    CMD=wget
+  else
+    echo "We require either cURL or wget. Install either one and try again."
+    exit 1
+  fi
+fi
+
 # Do the downloading.
 for station in "${STATIONS[@]}"; do
   
@@ -148,12 +158,22 @@ for station in "${STATIONS[@]}"; do
           ;;
       esac
       
-
-      curl --silent \
-        "http://climate.weather.gc.ca/climate_data/bulk_data_e.html?"`
-        `"format=csv&stationID=${station}&Year=${year}&Month=${month}&Day=14"`
-        `"&timeframe=${TIMEFRAME}&submit=Download+Data" -o \
-        "${station}-${period}${fileyr}${filemth}.csv";
+      URL="http://climate.weather.gc.ca/climate_data/bulk_data_e.html?"`
+            `"format=csv&stationID=${station}&Year=${year}&Month=${month}&Day=14"`
+            `"&timeframe=${TIMEFRAME}&submit=Download+Data"
+      OUT="${station}-${period}${fileyr}${filemth}.csv"
+      
+      echo "Downloading ${OUT} via ${CMD}"
+      
+      if [ "${CMD}" = "curl" ]; then
+        curl --silent "${URL}" -o "${OUT}"
+      elif [ "${CMD}" = "wget" ]; then
+        wget --content-disposition "${URL}" -O "${OUT}"
+      else
+        # This should be impossible.
+        echo "We got an unexpected download command. Please report the error!"
+        exit 1
+      fi
       
       if [ "${GUESSSKIP}" = "true" ]; then
         SKIP=$(awk 'length > m { m = length; a = NR } END { print a }' \
